#!/bin/bash
#
# Easy git push

source .pushpath

bla=`tput setaf 0`	#black color.
red=`tput setaf 1`      #red color.
gre=`tput setaf 2`      #green color.
yel=`tput setaf 3`      #yellow color.
blu=`tput setaf 4`	#blue color.
mag=`tput setaf 5`	#magenta color.
cya=`tput setaf 6`	#cyan color.
whi=`tput setaf 7`	#white color

clear

tput setaf 5

echo ""
echo ""
echo ""
echo "   _____ _____ _______   _____  _    _  _____ _    _ "
echo "  / ____|_   _|__   __| |  __ \| |  | |/ ____| |  | |"
echo " | |  __  | |    | |    | |__) | |  | | (___ | |__| |"
echo " | | |_ | | |    | |    |  ___/| |  | |\___ \|  __  |"
echo " | |__| |_| |_   | |    | |    | |__| |____) | |  | |"
echo "  \_____|_____|  |_|    |_|     \____/|_____/|_|  |_|"
echo ""
echo ""
echo ""

tput sgr0

if [ ! -e ./.pushpath ]; then
touch .pushpath
echo "#!/bin/bash" > .pushpath
echo "$yel The following path will be remembered by the script."
echo "$red Insert your path for the push: "
read filepath
tput sgr0

echo "path=$filepath" >> .pushpath
echo "$gre Path saved in ./.pushpath"
echo ""
echo ""
echo ""

echo -n "$gre Insert filename: "
echo "$gre $path"
read file
git add $file

echo "$yel Insert comment for the file"
echo -n "$yel Commit: "
read comm
git commit -m "$comm"

echo "$gre Insert repository"
echo -n "$gre Repository: "
read repo
tput setaf 3
git push -uf $repo master
tput sgr0 #return to original color.

else

echo "$gre Insert filename"
echo -n "$gre $path"
read file
git add $file

echo "$yel Insert comment for the file"
echo -n "$yel Commit: "
read comm
git commit -m "$comm"

echo "$gre Insert repository"
echo -n "$gre Repository: "
read repo
tput setaf 3
git push -uf $repo master
tput sgr0 #return to original color.

fi
tput setaf 5

echo ""
echo ""
echo ""
echo "  _______ _    _          _   _ _  __ _____   ______ ____  _____    _    _  _____ _____ _   _  _____ _ "
echo " |__   __| |  | |   /\   | \ | | |/ // ____| |  ____/ __ \|  __ \  | |  | |/ ____|_   _| \ | |/ ____| |"
echo "    | |  | |__| |  /  \  |  \| | ' /| (___   | |__ | |  | | |__) | | |  | | (___   | | |  \| | |  __| |"
echo "    | |  |  __  | / /\ \ | . ` |  <  \___ \  |  __|| |  | |  _  /  | |  | |\___ \  | | | . ' | | |_ | |"
echo "    | |  | |  | |/ ____ \| |\  | . \ ____) | | |   | |__| | | \ \  | |__| |____) |_| |_| |\  | |__| |_|"
echo "    |_|  |_|  |_/_/    \_|_| \_|_|\_|_____/  |_|    \____/|_|  \_\  \____/|_____/|_____|_| \_|\_____(_)"
echo ""
echo ""
echo ""

tput sgr0 #return to original color.
