#!/bin/bash
#
# Easy git push

source .pushpath
pun=`tput setaf 1`      #pun = red color.
roh=`tput setaf 2`      #roh = green color.
kol=`tput setaf 3`      #kol = yellow color.

clear
if [ ! -e ./.pushpath ]; then
touch .pushpath
echo "#!/bin/bash" > .pushpath
echo "$kol The following path will be remembered by the script."
echo "$pun Insert your path for the push: "
read filepath
tput sgr0

echo "path=$filepath" >> .pushpath
echo "$roh Path saved in ./.pushpath"
echo ""
echo ""

echo "$roh Insert filename"
echo -n "$roh $path"
read file
git add $file

echo "$kol Insert comment for the file"
echo -n "$kol Commit: "
read comm
git commit -m "$comm"

echo "$roh Insert repository"
echo -n "$roh Repository: "
read repo
tput setaf 3
git push -uf $repo master
tput sgr0 #return to original color.

else

echo "$roh Insert filename"
echo -n "$roh $path"
read file
git add $file

echo "$kol Insert comment for the file"
echo -n "$kol Commit: "
read comm
git commit -m "$comm"

echo "$roh Insert repository"
echo -n "$roh Repository: "
read repo
tput setaf 3
git push -uf $repo master
tput sgr0 #return to original color.

fi
tput sgr0 #return to original color.
